### ISSUE TITLE
Call JsMethod <doAction> Error，希望大佬能帮忙排查一下原因

### ISSUE THREAD

**Issue by suchen2** [pengwei1024/JsBridge#33]
版本：2.1.1
情况：升级了一下友盟的SDK，然后js页面加载就报错了
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/30523319/107213268-1f92ce80-6a43-11eb-96f8-e308effbe40d.png">

报错：
Call JsMethod <doAction> Error
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.apkfuns.jsbridge.f.a(JsMethod.java:130)
        at com.apkfuns.jsbridge.e.a(JsBridgeImpl.java:302)
        at com.apkfuns.jsbridge.e.callJsPrompt(JsBridgeImpl.java:151)
        at NewWebChromeClient.onJsPrompt(NewWebChromeClient.java:41)
        at W5.run(chromium-TrichromeWebViewGoogle.aab-stable-432415233:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7804)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/umeng/social/tool/UMImageMark;
        at java.lang.Class.getDeclaredFields(Native Method)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:152)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:458)
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/30523319/107213432-5cf75c00-6a43-11eb-9c3a-7c3be89249d7.png">

**Comment by pengwei1024** [comment]
混淆导致的吧，把 jsbridge 这几个类 keep 试试呢

**Comment by pengwei1024** [comment]
刚看到错误码，应该是你 UMImageMark 这个类没有打到包里面，然后你在 method 里面调用了，就被这里 cache 住了，跟 jsbridge 没有关系

**Comment by suchen2** [comment]
我也怀疑混淆的原因，但是我没有开混淆，UMImageMark这个类我找了一下之前没问题的版本，里面也没有，我很好奇JSBridge怎么会跟友盟的类扯上关系呢，好奇怪

**Comment by suchen2** [comment]
我也怀疑混淆的原因，但是我没有开混淆，UMImageMark这个类我找了一下之前没问题的版本，里面也没有，我很好奇JSBridge怎么会跟友盟的类扯上关系呢，好奇怪

**Comment by pengwei1024** [comment]
肯定是你某个 JsModule 实现类依赖了  UMImageMark， 还有可能就是在使用的时候这个类还没加载，你们可以自己排查下

**Comment by suchen2** [comment]
我看到在JSModule里解析的JavaBean中定义了UMImage,这个类是友盟的，但是类在源码里搜索不到，应该就是这里的问题，谢谢了
